import { PromptConfig } from './validation';

const CATEGORY_LABELS: Record<string, string> = {
  'portfolio': 'Portfolio Website',
  'agency': 'Creative Agency',
  'ecommerce': 'E-Commerce Store',
  'saas': 'SaaS Application',
  'dashboard': 'Admin Dashboard',
  'blog': 'Blog / Content Site',
  'educational': 'Educational Platform',
  'landing-page': 'Landing Page',
  'booking': 'Booking Platform',
  'marketplace': 'Marketplace',
  'custom': 'Custom Project',
};

const DESIGN_LABELS: Record<string, string> = {
  'reference-inspired': 'Inspired by the reference website',
  'luxury': 'Luxury / Premium aesthetic',
  'minimal': 'Clean and minimal',
  'editorial': 'Editorial / Magazine style',
  'brutalist': 'Brutalist / Bold',
  'futuristic': 'Futuristic / Tech-forward',
  'playful': 'Playful / Creative',
  'corporate': 'Corporate / Professional',
  'custom': 'Custom direction',
};

const TECH_LABELS: Record<string, string> = {
  'nextjs': 'Next.js (App Router, React Server Components)',
  'react': 'React with Vite',
  'vue': 'Vue.js 3 with Composition API',
  'html-css-js': 'Plain HTML, CSS, and JavaScript',
  'nodejs': 'Node.js with Express',
  'java-spring': 'Java with Spring Boot',
  'custom': 'Custom stack',
};

const AGENT_LABELS: Record<string, string> = {
  'qwen-code': 'Qwen Code',
  'claude-code': 'Claude Code',
  'cursor': 'Cursor',
  'github-copilot': 'GitHub Copilot',
  'generic': 'Generic AI Coding Agent',
};

const ANIMATION_LABELS: Record<string, string> = {
  'minimal': 'Minimal — subtle transitions only',
  'polished': 'Polished — smooth animations with purpose',
  'advanced': 'Advanced — complex animations and micro-interactions',
};

function section(title: string, content: string): string {
  return `\n## ${title}\n\n${content}\n`;
}

function bulletList(items: string[]): string {
  return items.filter(Boolean).map(item => `- ${item}`).join('\n');
}

export function generatePrompt(config: PromptConfig, referenceAnalysis?: string): string {
  const designDir = config.designDirection === 'custom' && config.customDesignDirection
    ? config.customDesignDirection
    : DESIGN_LABELS[config.designDirection] || config.designDirection;

  const techStack = config.techStack === 'custom' && config.customTechStack
    ? config.customTechStack
    : TECH_LABELS[config.techStack] || config.techStack;

  const agentName = AGENT_LABELS[config.codingAgent] || config.codingAgent;

  let prompt = `# AI Implementation Prompt\n\n`;
  prompt += `> Generated by AI Prompt Studio for ${agentName}\n`;
  prompt += `> Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}\n`;

  // 1. Role and Objective
  prompt += section('1. Role and Objective', `You are an expert ${config.experienceLevel === 'beginner' ? 'patient, educational' : 'senior'} full-stack developer. Your task is to build a complete, production-ready ${CATEGORY_LABELS[config.projectCategory] || 'web application'} based on the requirements below.

**Target Agent:** ${agentName}
**Experience Level:** ${config.experienceLevel === 'beginner' ? 'Beginner-friendly with detailed explanations and comments' : 'Expert-oriented with concise, production-grade implementation'}

The output must be a fully functional application that can be deployed immediately after setup.`);

  // 2. Project Context
  prompt += section('2. Project Context and Requirements', `**Description:**
${config.projectDescription}

**Category:** ${CATEGORY_LABELS[config.projectCategory] || config.projectCategory}
**Design Direction:** ${designDir}
**Visual Theme:** ${config.visualTheme === 'automatic' ? 'Automatic (match design direction)' : config.visualTheme}
**Technology Stack:** ${techStack}
**Animation Level:** ${ANIMATION_LABELS[config.animationLevel] || config.animationLevel}
**Deployment Target:** ${config.deploymentTarget}
**Responsive Targets:** ${config.responsiveTargets.join(', ')}`);

  if (config.referenceUrl) {
    prompt += `\n**Reference URL:** ${config.referenceUrl}\n`;
  }

  // 3. Reference Analysis
  if (referenceAnalysis) {
    prompt += section('3. Reference Website Analysis', `${referenceAnalysis}

> Note: These observations are based on publicly accessible information. The implementation should be inspired by the reference, not a direct copy. Create original code, designs, and content.`);
  } else if (config.referenceUrl) {
    prompt += section('3. Reference Website', `A reference URL was provided (${config.referenceUrl}) but could not be automatically analyzed. Use the URL as inspiration for the overall feel and structure, but create an entirely original implementation. Do not attempt to reproduce the reference site's exact content, branding, or proprietary elements.`);
  }

  // 4. Design System
  prompt += section('4. Design System and Visual Direction', `**Direction:** ${designDir}

**Design Principles:**
- Consistent spacing scale (4px/8px base unit)
- Harmonious color palette with primary, secondary, accent, and neutral tones
- Typography scale with clear hierarchy (h1-h6, body, caption)
- Consistent border radius, shadows, and elevation
- ${config.animationLevel === 'minimal' ? 'Subtle hover states and transitions (150-200ms)' : config.animationLevel === 'polished' ? 'Smooth animations with easing curves, page transitions, and loading states' : 'Complex animations including scroll-triggered effects, parallax, staggered reveals, and micro-interactions'}

**Color System:**
- Define CSS custom properties or theme tokens for all colors
- Support both light and dark modes ${config.visualTheme === 'automatic' || config.visualTheme === 'custom' ? '(implement both)' : `(implement ${config.visualTheme} mode)`}
- Ensure WCAG AA contrast ratios for all text

**Typography:**
- Use a modern, readable font stack (Inter, system-ui, or similar sans-serif)
- Establish a clear type scale with consistent line heights
- Use monospace font for code blocks`);

  // 5. Pages
  prompt += section('5. Page-by-Page Requirements', config.requiredPages
    ? `Build the following pages and sections:\n\n${config.requiredPages}`
    : `Create a sensible page structure for a ${CATEGORY_LABELS[config.projectCategory] || 'web application'}:

- Home/Landing page with hero section, features, social proof, and CTA
- ${config.projectCategory === 'ecommerce' ? 'Product listing, product detail, cart, checkout' : ''}
- ${config.projectCategory === 'saas' ? 'Features, pricing, about, documentation' : ''}
- ${config.projectCategory === 'dashboard' ? 'Dashboard overview, data tables, settings, user management' : ''}
- ${config.projectCategory === 'blog' ? 'Blog listing, individual post, categories, about' : ''}
- About page
- Contact page with form
- 404 error page

Adapt the structure to best serve the project's purpose.`);

  // 6. Components
  prompt += section('6. Components and Component Hierarchy', `Create a well-organized component library:

**Layout Components:**
- Header/Navigation with responsive mobile menu
- Footer with links and social icons
- Page layout wrapper
- Sidebar (if applicable)

**UI Components:**
- Button (primary, secondary, ghost, destructive variants)
- Input, Textarea, Select, Checkbox, Radio
- Card, Modal/Dialog, Toast/Notification
- Badge, Avatar, Progress indicator
- Accordion, Tabs, Dropdown menu

**Feature Components:**
- Hero section with compelling headline and CTA
- Feature grid/cards
- Testimonials/social proof section
- Pricing table (if applicable)
- Contact form with validation
- Navigation with active state indicators

**Patterns:**
- Reusable form components with validation states
- Loading skeletons for async content
- Empty states with helpful messaging
- Error boundaries with recovery options`);

  // 7. Architecture
  prompt += section('7. Framework and Architecture', `**Stack:** ${techStack}

**Architecture Principles:**
- Component-based architecture with clear separation of concerns
- ${config.techStack === 'nextjs' ? 'App Router with Server Components where possible, Client Components for interactivity' : ''}
- ${config.techStack === 'react' ? 'Vite for fast development, React Router for navigation' : ''}
- ${config.techStack === 'vue' ? 'Composition API with setup scripts, Vue Router' : ''}
- Type-safe throughout (${config.techStack === 'html-css-js' ? 'use JSDoc comments' : 'TypeScript'})
- State management appropriate to complexity (${config.projectCategory === 'dashboard' ? 'Zustand or Redux for complex state' : 'React Context or local state'})
- API routes or serverless functions for backend logic
- Environment variables for configuration`);

  // 8. Functional Behavior
  prompt += section('8. Functional Behavior and State Management', config.requiredFunctionality
    ? `**Required Functionality:**\n${config.requiredFunctionality}`
    : `Implement the following functional requirements:

- Client-side form validation with helpful error messages
- Smooth page transitions and navigation
- Loading states for all async operations
- Optimistic updates where appropriate
- Error handling with user-friendly messages
- Data persistence (localStorage for client-side, database for server-side)
- Search and filtering capabilities where relevant
- Pagination for list views`);

  if (config.authDbApi) {
    prompt += `\n**Authentication & Data:**\n${config.authDbApi}\n`;
  }

  // 9. Responsive
  prompt += section('9. Responsive Requirements', `**Target Breakpoints:**
${config.responsiveTargets.map(t => {
  switch(t) {
    case 'mobile': return '- Mobile: 320px - 767px (primary touch target, stacked layouts)';
    case 'tablet': return '- Tablet: 768px - 1023px (hybrid layouts, touch-friendly)';
    case 'desktop': return '- Desktop: 1024px+ (full layouts, hover states, multi-column)';
    default: return '';
  }
}).join('\n')}

**Responsive Strategy:**
- Mobile-first CSS approach
- Flexible grid system using CSS Grid and Flexbox
- Responsive images with srcset and lazy loading
- Touch-friendly tap targets (minimum 44x44px)
- No horizontal overflow at any breakpoint
- Test at all target breakpoints before completion`);

  // 10. Animation
  prompt += section('10. Animation and Interaction Specifications', `**Level:** ${ANIMATION_LABELS[config.animationLevel]}

${config.animationLevel === 'minimal' ? `
- CSS transitions on hover/focus states (150-200ms)
- Smooth scroll behavior
- Basic fade-in on page load
` : config.animationLevel === 'polished' ? `
- Page transition animations (fade/slide, 300-400ms)
- Staggered list item animations
- Scroll-triggered reveal animations (intersection observer)
- Smooth hover effects with easing curves
- Loading skeleton animations
- Toast/notification slide-in animations
- Modal open/close transitions
` : `
- All polished animations plus:
- Parallax scrolling effects
- Complex scroll-triggered sequences
- Animated counters and progress indicators
- Magnetic button effects
- Text reveal animations
- Card tilt/3D effects on hover
- Page transition choreography
- Animated SVG illustrations
- Particle or gradient background animations
`}
**Performance Rules:**
- Respect \`prefers-reduced-motion\` media query
- Use CSS transforms and opacity for GPU-accelerated animations
- Use \`will-change\` sparingly and only when needed
- Keep animations under 500ms for UI feedback
- Use requestAnimationFrame for JS-driven animations`);

  // 11. Accessibility
  prompt += section('11. Accessibility and Semantic HTML', config.seoAccessibility
    ? `**SEO & Accessibility Requirements:**\n${config.seoAccessibility}`
    : `**Accessibility (WCAG 2.1 AA):**
- Semantic HTML5 elements (header, nav, main, section, article, footer)
- Proper heading hierarchy (h1-h6)
- ARIA labels for interactive elements
- Keyboard navigation for all interactive components
- Visible focus indicators
- Color contrast ratios meeting WCAG AA (4.5:1 for text)
- Alt text for all images
- Form labels associated with inputs
- Error messages linked to form fields
- Skip navigation link

**SEO:**
- Descriptive page titles and meta descriptions
- Open Graph and Twitter Card meta tags
- Structured data (JSON-LD) where appropriate
- Sitemap.xml and robots.txt
- Canonical URLs
- Semantic markup for search engines
- Fast page load times (Core Web Vitals optimized)`);

  // 12. Performance
  prompt += section('12. Performance Requirements', `**Core Web Vitals Targets:**
- LCP (Largest Contentful Paint): < 2.5s
- FID (First Input Delay): < 100ms
- CLS (Cumulative Layout Shift): < 0.1

**Optimization Strategies:**
- Code splitting and lazy loading for routes
- Image optimization (WebP, responsive sizes, lazy loading)
- Font optimization (preload, font-display: swap)
- Minimize JavaScript bundle size
- CSS purging for unused styles
- Caching strategies for static assets
- ${config.techStack === 'nextjs' ? 'Server-side rendering / static generation where appropriate' : 'Pre-rendering critical content'}
- Compress assets with gzip/brotli`);

  // 13. Security
  prompt += section('13. Security and Privacy Requirements', `- Never expose API keys or secrets in client-side code
- Validate and sanitize all user inputs
- Use parameterized queries for database operations
- Implement CSRF protection for forms
- Set appropriate security headers (CSP, X-Frame-Options, etc.)
- Use HTTPS in production
- Rate limit API endpoints
- Sanitize HTML output to prevent XSS
- Store sensitive data securely (hashed passwords, encrypted tokens)
- Implement proper CORS configuration
- Follow the principle of least privilege`);

  // 14. Environment
  prompt += section('14. Environment Variables and Integration Setup', `Provide a \`.env.example\` file with all required environment variables (placeholder names only, no real values):

\`\`\`
# Application
NEXT_PUBLIC_APP_URL=
NODE_ENV=

# Database (if applicable)
DATABASE_URL=

# Authentication (if applicable)
AUTH_SECRET=

# External Services (if applicable)
API_KEY_PLACEHOLDER=
\`\`\`

Document each variable's purpose and how to obtain it.`);

  // 15. File Structure
  prompt += section('15. Project File Structure', `${config.techStack === 'nextjs' ? `
\`\`\`
├── app/
│   ├── layout.tsx
│   ├── page.tsx
│   ├── globals.css
│   ├── (routes)/
│   │   ├── about/
│   │   ├── contact/
│   │   └── ...
│   └── api/
│       └── ...
├── components/
│   ├── ui/
│   ├── layout/
│   └── features/
├── lib/
│   ├── utils.ts
│   └── constants.ts
├── public/
├── types/
├── .env.example
├── tailwind.config.ts
├── tsconfig.json
└── package.json
\`\`\`
` : config.techStack === 'react' ? `
\`\`\`
├── src/
│   ├── components/
│   │   ├── ui/
│   │   ├── layout/
│   │   └── features/
│   ├── pages/
│   ├── hooks/
│   ├── lib/
│   ├── types/
│   ├── App.tsx
│   └── main.tsx
├── public/
├── .env.example
├── tailwind.config.js
├── vite.config.ts
└── package.json
\`\`\`
` : `Organize files logically by feature/domain with clear separation between components, styles, utilities, and configuration.`}`);

  // 16. Implementation Plan
  prompt += section('16. Phased Implementation Plan', `**Phase 1: Foundation**
- Initialize project with ${techStack.split('(')[0].trim()}
- Set up Tailwind CSS and design tokens
- Create base layout components (Header, Footer, Layout)
- Configure routing and navigation

**Phase 2: Core Pages**
- Build the home/landing page with hero section
- Create all required pages with placeholder content
- Implement responsive layouts for all breakpoints

**Phase 3: Components and Interactions**
- Build reusable UI component library
- Add animations and transitions
- Implement form validation and interactions
- Add loading states and error handling

**Phase 4: Functionality**
- Implement required features and integrations
- Add data fetching and state management
- Connect any external APIs or services
- Implement authentication if required

**Phase 5: Polish and Deploy**
- Optimize performance (images, code splitting, caching)
- Audit accessibility (keyboard nav, screen readers, contrast)
- SEO optimization (meta tags, structured data, sitemap)
- Testing across browsers and devices
- Deploy to ${config.deploymentTarget}`);

  // 17. Testing
  prompt += section('17. Testing and Validation Commands', `\`\`\`bash
# Development
npm run dev

# Build for production
npm run build

# Type checking
npm run typecheck

# Linting
npm run lint

# Run tests
npm test

# Preview production build
npm run preview
\`\`\`

**Manual Testing Checklist:**
- [ ] All pages render correctly
- [ ] Navigation works on all breakpoints
- [ ] Forms validate and submit correctly
- [ ] Animations play smoothly without jank
- [ ] Dark/light mode toggles correctly
- [ ] Keyboard navigation works throughout
- [ ] No console errors or warnings
- [ ] Page load time is acceptable
- [ ] Images load with proper sizing`);

  // 18. Acceptance Criteria
  prompt += section('18. Acceptance Criteria', bulletList([
    'Application builds without errors or TypeScript warnings',
    'All pages are responsive at mobile, tablet, and desktop breakpoints',
    'Navigation is fully keyboard-accessible',
    'Color contrast meets WCAG AA standards',
    'All interactive elements have visible focus states',
    'Forms have proper validation and error messaging',
    'No horizontal overflow at any viewport width',
    'Animations respect prefers-reduced-motion',
    'All images have descriptive alt text',
    'Meta tags are properly configured for SEO',
    'Environment variables are documented in .env.example',
    config.experienceLevel === 'beginner' ? 'Code includes helpful comments explaining key decisions' : 'Code follows production best practices and patterns',
    'Application can be deployed to ' + config.deploymentTarget + ' with documented steps',
  ]));

  // 19. Deployment
  prompt += section('19. Deployment Instructions', `**Target:** ${config.deploymentTarget}

${config.deploymentTarget === 'vercel' ? `
1. Push code to a Git repository (GitHub, GitLab, or Bitbucket)
2. Import the project in Vercel Dashboard
3. Configure environment variables in Vercel project settings
4. Deploy (automatic on push to main branch)
5. Configure custom domain if needed
` : config.deploymentTarget === 'aws' ? `
1. Build the production bundle: \`npm run build\`
2. Configure AWS services (S3 + CloudFront, or ECS, or Amplify)
3. Set up environment variables in the deployment environment
4. Configure DNS and SSL certificate
5. Set up CI/CD pipeline with GitHub Actions or CodePipeline
` : config.deploymentTarget === 'self-hosted' ? `
1. Build the production bundle: \`npm run build\`
2. Configure your server (Nginx, Apache, or Docker)
3. Set up environment variables on the server
4. Configure reverse proxy and SSL (Let's Encrypt)
5. Set up process management (PM2, systemd)
6. Configure monitoring and logging
` : `
1. Follow your hosting provider's deployment documentation
2. Build the production bundle: \`npm run build\`
3. Configure environment variables
4. Set up SSL and domain configuration
`}`);

  // 20. Assumptions
  prompt += section('20. Known Assumptions and Limitations', bulletList([
    'This prompt was generated based on the provided description and configuration',
    config.referenceUrl ? `Reference URL (${config.referenceUrl}) was ${referenceAnalysis ? 'analyzed and findings are noted above' : 'not automatically analyzed — implementation should be inspired, not copied'}` : 'No reference URL was provided — design is based entirely on the description',
    'External service integrations require valid API credentials',
    'Content (text, images, data) should be replaced with real project content',
    'Performance may vary based on hosting infrastructure and traffic',
    'Browser support targets modern evergreen browsers (Chrome, Firefox, Safari, Edge — last 2 versions)',
    'Third-party dependencies should be reviewed for security before production use',
  ]));

  return prompt;
}

export function estimateTokens(prompt: string): number {
  // Rough estimate: ~4 characters per token for English text
  return Math.ceil(prompt.length / 4);
}
